server:
  port: 10010
spring:
  application:
    name: gateway-service
#zuul:
#  routes:
#    user-service:
#      path: /user-service/** # 这里是映射路径
#      serviceId: user-service # 指定服务名称
zuul:
  prefix: /api  #添加路由前缀
  routes:
    user-service: /user-service/** #简化配置
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  ignored-services:
    - consumer-service

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
#      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

